name: depcruise
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  depcruise:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # ① 先に pnpm を入れる（ここで PATH に通る）
      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      # ② その後で node をセットしつつ pnpm キャッシュを有効化
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'   # ← ここで pnpm が実在するので失敗しない

      - name: Install deps
        run: pnpm install --frozen-lockfile || pnpm install

      - name: Run depcruise & annotate
        run: pnpm run depcruise:ci
