name: depcruise
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  depcruise:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          version: 9
          run_install: false

      # ★ pnpm を Corepack で有効化（ここが必須）
      - name: Enable pnpm via Corepack
        run: |
          corepack enable
          corepack prepare pnpm@9 --activate
          pnpm --version

      - name: Install deps
        run: pnpm install --frozen-lockfile || pnpm install

      - name: Run dependency-cruiser
        run: pnpm run depcruise

      - name: Annotate violations (Files changed)
        run: pnpm run depcruise:annotate

      - name: Upload depcruise.json
        uses: actions/upload-artifact@v4
        with:
          name: depcruise-report
          path: depcruise.json
